services:
  - type: web
    name: hotel-booking-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: USE_MOCK_DATA
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - templates/**
        - static/**
        - hotel_providers.py 