services:
  - type: web
    name: hotel-booking-system
    env: python
    region: oregon
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn==20.1.0
    startCommand: |
      export PATH=$PATH:/usr/local/bin
      gunicorn app:app --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: .
      - key: RENDER_EXTERNAL_URL
        value: https://hotel-booking-system.onrender.com 