services:
  - type: web
    name: hotel-booking-system-v2
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m pytest tests/
    startCommand: gunicorn main:app
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /health
    autoDeploy: true
    branch: main