services:
  - type: web
    name: hotel-booking-system
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p templates static
      echo '<!DOCTYPE html><html><head><title>Hotel Booking System</title></head><body><h1>Hotel Booking System</h1><p>Version 2.1</p></body></html>' > templates/index.html
      touch __init__.py
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: USE_MOCK_DATA
        value: "true"
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: PORT
        value: "10000"
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - "**/*.py"
        - requirements.txt
        - templates/**
        - static/**
        - .env
        - __init__.py
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 