services:
  - type: web
    name: hotel-booking-system
    env: python
    plan: free
    buildCommand: |
      python3.9 -m pip install --upgrade pip
      python3.9 -m pip install -r requirements.txt
    startCommand: python3.9 -m uvicorn app.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: USE_MOCK_DATA
        value: "true"
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - app/**/*.py
        - requirements.txt
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 