services:
  - type: web
    name: hotel-booking-system
    env: python
    region: oregon
    plan: free
    buildCommand: chmod +x build.sh
    startCommand: ./build.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: . 