services:
  - type: web
    name: hotel-booking-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 4
    envVars:
      - key: BOOKING_API_KEY
        sync: false
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: true
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 