services:
  - type: web
    name: hotel-booking-system-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildFilter:
      paths:
        - main.py
        - app/**
        - requirements.txt
        - static/**
        - .env
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache