services:
  - type: web
    name: hotel-booking-system-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: PORT
        value: 8000
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildFilter:
      paths:
        - app/**
        - requirements.txt
        - templates/**
        - static/**
        - .env
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache