services:
  - type: web
    name: hotel-booking-system-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3.9 -m uvicorn app.app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 