services:
  - type: static
    name: hotel-booking-system
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18.x
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
    healthCheckPath: /api/health
    buildFilter:
      paths:
        - src/**/*.ts
        - public/**/*
        - package.json
        - tsconfig.json
