services:
  - type: web
    name: hotel-booking-system
    env: python
    buildCommand: chmod +x build.sh start.sh && ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
      - key: FLASK_APP
        value: wsgi:app
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    buildFilter:
      paths:
        - "**/*.py"
        - "requirements.txt"
        - "static/**"
        - "templates/**"
        - "build.sh"
        - "start.sh"
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 