services:
  - type: web
    name: hotel-booking-system-v2
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120 --log-level debug
    envVars:
      - key: PORT
        value: 8000
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildFilter:
      paths:
        - main.py
        - app/**
        - requirements.txt
        - static/**
        - .env
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache