services:
  - type: web
    name: hotel-booking-system
    runtime: node
    buildCommand: |
      npm install
      npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    staticPublishPath: ./dist/public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    healthCheckPath: /api/health
    buildFilter:
      paths:
        - src/**/*.ts
        - public/**/*
        - package.json
        - tsconfig.json
