services:
  - type: web
    name: hotel-booking-system
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb://localhost:27017/hotel-booking
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
