services:
  - type: web
    name: hotel-booking-system
    env: python
    buildCommand: |
      python3 -m pip install --upgrade pip
      pip3 install -r requirements.txt
    startCommand: python3 -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: USE_MOCK_DATA
        value: "true"
      - key: PYTHONPATH
        value: .
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - "**/*.py"
        - requirements.txt
        - templates/**
        - static/**
        - .env
        - README.md 