services:
  - type: web
    name: hotel-booking-system-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/main.py
    envVars:
      - key: PORT
        value: 8000
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - templates/**
        - static/**
        - hotel_booking_system_v2.py
        - .env
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 