services:
  - type: web
    name: hotel-booking-system
    env: python
    buildCommand: |
      python3 -m pip install --upgrade pip
      python3 -m pip install --no-cache-dir -r requirements.txt
    startCommand: python3 -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: PYTHONPATH
        value: .
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: GOOGLE_HOTELS_CLIENT_ID
        sync: false
      - key: API_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        value: https://${RENDER_EXTERNAL_HOSTNAME}
      - key: USE_MOCK_DATA
        value: "true"
      - key: PIP_NO_CACHE_DIR
        value: "true"
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: hotel-booking-data
      mountPath: /data
      sizeGB: 1
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - templates/**
        - static/**
        - hotel_booking_system_v2.py
        - hotel_providers.py
        - middleware.py
        - validators.py
        - setup_api_keys.py
        - mock_data/**
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 