services:
  - type: web
    name: hotel-booking-system
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
      - key: USE_MOCK_DATA
        value: "true"
      - key: PYTHONPATH
        value: .
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - templates/**
        - static/**
        - hotel_providers.py
        - hotel_booking_system_v2.py
        - middleware.py
        - validators.py
        - .env
        - README.md 