services:
  - type: web
    name: hotel-booking-system-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /health
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 