services:
  - type: web
    name: hotel-booking-system
    env: python
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    buildFilter:
      paths:
        - "**/*.py"
        - "requirements.txt"
        - "static/**"
        - "templates/**"
        - "build.sh"
        - "start.sh"
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 