services:
  - type: web
    name: hotel-booking-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT --workers 4
    envVars:
      - key: BOOKING_API_KEY
        value: test_api_key_123456789
      - key: GOOGLE_HOTELS_API_KEY
        value: AIzaSyDxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX
      - key: GOOGLE_HOTELS_CLIENT_ID
        value: 123456789-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /
    autoDeploy: true
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    buildFilter:
      paths:
        - app.py
        - requirements.txt
        - templates/**
        - static/**
        - hotel_booking_system_v2.py
        - .env
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 