name: Deploy to Render and Monitor Status

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  RENDER_API_KEY: rnd_BeGGfY5yYXdVetFn5BhVHGwShzmb
  RENDER_SERVICE_ID: srv-cvdmg2ofnakc73d4tkg0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Render
        run: |
          echo "Triggering deployment..."
          curl -X POST https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys \
            -H "Authorization: Bearer $RENDER_API_KEY"
          
      - name: Monitor Deployment Status
        run: |
          echo "Starting deployment status monitoring..."
          while true; do
            STATUS=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
              "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" | \
              jq -r '.[0].status')
            
            if [ "$STATUS" = "live" ]; then
              echo "✅ Deployment successful!"
              exit 0
            elif [ "$STATUS" = "failed" ]; then
              echo "❌ Deployment failed!"
              exit 1
            else
              echo "⏳ Deployment in progress... Status: $STATUS"
              sleep 30
            fi
          done
